
services:
#  db:
#    image: postgres:16-alpine
#    container_name: organiq_db
#    environment:
#      POSTGRES_DB: organiq
#      POSTGRES_USER: organiq
#      POSTGRES_PASSWORD: organiq
#    ports:
#      - "5432:5432"
#    volumes:
#      - organiq_pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${APP_ENV}
    container_name: organiq_api
    env_file:
      - ./.env
    environment:
      APP_ENV: ${APP_ENV}
      PORT: 8080
      DATABASE_URL: ${DATABASE_URL}
      GOOGLE_APPLICATION_CREDENTIALS: /config/firebase-admin.json
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./:/app
      - ./config:/config:ro
    command: ["air", "-c", ".air.toml"]
    ports:
      - "8080:8080"
#    depends_on:
#      - db

#volumes:
#  organiq_pgdata:
